# Welcome to Jekyll!
title: Ben Matheja
email: ben@matheja.me
author:
  name: Ben Matheja
  email: ben@matheja.me
minima:
  social_links:
    twitter: benmatheja
    github:  BenMatheja
    linkedin: benmatheja
header_pages:
  - about.md
  - readinglist.md
description: | # this means to ignore newlines until "baseurl:"
  Product Owner @porsche 
  | All things Cloud | Product Management | Agile Methods | posts are my own opinion

show_excerpts: true
excerpt_separator: <!--more-->
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matheja.me" # the base hostname & protocol for your site, e.g. http://example.com
  # generate social links in footer
google_analytics: UA-90631871-7

# Resume settings
resume_avatar:                  "true"
resume_title:                   "Product Owner Digital Service"
# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_address:         "Mittbachweg 16, Wächtersbach"

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: |
  <p> Ben is working as a Product Owner in the automotive domain 
  blending agile methods, Product Management techniques and strong technical expertise to realize digital products with impact</p>
  <p> I personally believe in teams as the pinnacle of innovation, in meaningful exchanges between skilled individuals and in the ability of responsible humans to facilitate decisions. </p>


# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          false
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
resume_section_interests:       false

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
